import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    // These suites mutate process-wide env/PATH and bind real local servers.
    // Keep files serial so fake agent binaries stay scoped to their tests.
    fileParallelism: false,
    include: ['tests/**/*.test.{ts,tsx,js,mjs,cjs}'],
    // Inferno-only: skip suites that spawn unshipped CLI agents or require
    // claude/codex/amr/opencode in SHIPPED_AGENT_DEFS.
    exclude: [
      '**/node_modules/**',
      'tests/acp-handshake-failure-wiring.test.ts',
      'tests/acp-service-failure-wiring.test.ts',
      'tests/acp-stage-timeout-wiring.test.ts',
      'tests/acp-stdio-mcp-wiring.test.ts',
      'tests/agent-companion-setup.test.ts',
      'tests/amr-session-resume.test.ts',
      'tests/chat-project-skill-critique-label.test.ts',
      'tests/claude-sidechain-assistant-error-false-failure.test.ts',
      'tests/claude-sidechain-turn-end-false-success.test.ts',
      'tests/cli-phase2c.test.ts',
      'tests/codex-app-server-transport-switch.test.ts',
      'tests/codex-model-capability-preflight.test.ts',
      'tests/codex-session-resume.test.ts',
      'tests/deliverable-syntax-finalizer-server.test.ts',
      'tests/first-visible-output-mark.test.ts',
      'tests/first-visible-output-telemetry-isolation.test.ts',
      'tests/headless-runs.test.ts',
      'tests/integrations/vela-command.test.ts',
      'tests/integrations/vela-terminal-command.test.ts',
      'tests/integrations/vela-wallet.test.ts',
      'tests/integrations/vela.routes.test.ts',
      'tests/integrations/vela.test.ts',
      'tests/mcp-agent-install.test.ts',
      'tests/mcp-install-codex.test.ts',
      'tests/mcp-runs.test.ts',
      'tests/mcp-spawn.test.ts',
      'tests/media-failure-reaches-run-terminal.test.ts',
      'tests/od-next-advertised-capability-admission.test.ts',
      'tests/od-next-automatic-simple-server.test.ts',
      'tests/opencode-session-resume.test.ts',
      'tests/plugins-headless-run.test.ts',
      'tests/resume-continue-prompt-context.test.ts',
      'tests/retry-generation-terminal-fence.test.ts',
      'tests/retry-orphan-process-group.test.ts',
      'tests/run-atomic-ownership.test.ts',
      'tests/run-cli.test.ts',
      'tests/run-create-workspace-gate.test.ts',
      'tests/run-enrichment-dedupe.test.ts',
      'tests/run-event-truncation-artifact-verdict.test.ts',
      'tests/run-failure-detail-persisted-message.test.ts',
      'tests/run-failure-detail-status.test.ts',
      'tests/run-failure-stderr-tail-persisted-message.test.ts',
      'tests/run-failure-verdict-transport.test.ts',
      'tests/run-request-idempotency.test.ts',
      'tests/run-resume-on-failure.test.ts',
      'tests/run-retry-duplicate-answer.test.ts',
      'tests/run-retry-runtime.test.ts',
      'tests/run-retry-sse-wire.test.ts',
      'tests/run-steer-route.test.ts',
      'tests/run-terminal-produced-files-association.test.ts',
      'tests/runtimes/acp-stall-last-progress-age.test.ts',
      'tests/runtimes/amr-terminal-report-delivery.test.ts',
      'tests/runtimes/amr-terminal-reports.test.ts',
      'tests/runtimes/codex-child-evidence.test.ts',
      'tests/runtimes/codex-resume-args.test.ts',
      'tests/runtimes/deepseek-harness-windows.test.ts',
      'tests/runtimes/project-amr-trace-env.test.ts',
      'tests/runtimes/project-amr-workspace-proof.test.ts',
      'tests/runtimes/run-failure-telemetry-smoke.test.ts',
      'tests/stale-message-snapshot-preserves-daemon-events.test.ts',
      'tests/task-successor-absorption.test.ts',
      'tests/tool-token-startup-leak.test.ts',
      'tests/vela-media-safety-process.test.ts',
      'tests/w102-thinking-empty-delta-heartbeat.test.ts',
    ],
    setupFiles: ['tests/setup.ts'],
    testTimeout: 20_000,
  },
});
