export const INFERNO_ERROR_CODES = {
  KEY_REQUIRED: 'INFERNO_KEY_REQUIRED',
  NOT_READY: 'INFERNO_NOT_READY',
  KEY_REJECTED: 'INFERNO_KEY_REJECTED',
  RATE_LIMITED: 'INFERNO_RATE_LIMITED',
  UNAVAILABLE: 'INFERNO_UNAVAILABLE',
  MODEL_UNREACHABLE: 'INFERNO_MODEL_UNREACHABLE',
} as const;

export type InfernoErrorCode =
  (typeof INFERNO_ERROR_CODES)[keyof typeof INFERNO_ERROR_CODES];
